#!/usr/bin/env python3
"""
update_readme.py — Regenerates the AUTO-GENERATED block in README.md.

Updates a clearly delimited section between:
    <!-- AUTO-GENERATED:START -->
    ...
    <!-- AUTO-GENERATED:END -->

with the current timestamp and a list of all git branches and tags.

Usage:
    python scripts/update_readme.py [--readme PATH]

Exit codes:
    0  README was updated (or already up to date).
    1  README file not found or markers missing.
"""

import argparse
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

START_MARKER = "<!-- AUTO-GENERATED:START -->"
END_MARKER = "<!-- AUTO-GENERATED:END -->"

README_DEFAULT = Path(__file__).resolve().parent.parent / "README.md"


def run_git(*args: str) -> list[str]:
    """Run a git command and return non-empty output lines."""
    result = subprocess.run(
        ["git"] + list(args),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def get_branches() -> list[str]:
    """Return all remote branch names, excluding HEAD."""
    lines = run_git("branch", "-r", "--format=%(refname:short)")
    # Filter out HEAD pointers (e.g. origin/HEAD -> origin/main)
    return [
        line.removeprefix("origin/")
        for line in lines
        if "->" not in line
    ]


def get_tags() -> list[str]:
    """Return all tags, newest first (by version sort)."""
    return run_git("tag", "--sort=-version:refname")


def build_autogenerated_block(branches: list[str], tags: list[str]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    branch_lines = "\n".join(f"- `{b}`" for b in branches) if branches else "_(none found)_"
    tag_lines = "\n".join(f"- `{t}`" for t in tags) if tags else "_(none found)_"

    return f"""{START_MARKER}
<!-- This section is automatically updated by scripts/update_readme.py on every push. Do not edit manually. -->

## 📊 Evolution Snapshots

**Last updated:** {now}

### Branches
{branch_lines}

### Tags
{tag_lines}

{END_MARKER}"""


def update_readme(readme_path: Path) -> bool:
    """
    Update the auto-generated block in readme_path.

    Returns True if the file was modified, False if it was already up to date.
    Raises SystemExit on error.
    """
    if not readme_path.exists():
        print(f"ERROR: README not found at {readme_path}", file=sys.stderr)
        sys.exit(1)

    content = readme_path.read_text(encoding="utf-8")

    start_idx = content.find(START_MARKER)
    end_idx = content.find(END_MARKER)

    if start_idx == -1 or end_idx == -1:
        print(
            f"ERROR: Could not find markers '{START_MARKER}' / '{END_MARKER}' in {readme_path}",
            file=sys.stderr,
        )
        sys.exit(1)

    if end_idx < start_idx:
        print("ERROR: END marker appears before START marker.", file=sys.stderr)
        sys.exit(1)

    branches = get_branches()
    tags = get_tags()

    new_block = build_autogenerated_block(branches, tags)

    # Replace everything from START_MARKER to END_MARKER (inclusive)
    end_of_end = end_idx + len(END_MARKER)
    new_content = content[:start_idx] + new_block + content[end_of_end:]

    if new_content == content:
        print("README is already up to date.")
        return False

    readme_path.write_text(new_content, encoding="utf-8")
    print(f"README updated at {readme_path}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Update the auto-generated block in README.md")
    parser.add_argument(
        "--readme",
        type=Path,
        default=README_DEFAULT,
        help=f"Path to README.md (default: {README_DEFAULT})",
    )
    args = parser.parse_args()
    update_readme(args.readme)


if __name__ == "__main__":
    main()
